name: lifer
description: "A new Flutter project."
publish_to: "none"
version: 5.6.9+6

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_feather_icons: ^2.0.0+1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  fpdart: ^1.1.0
  get_it: ^8.0.0
  isar: ^4.0.0-dev.14
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
